server:
  port: ${SERVER_PORT:8091}
  shutdown: graceful
  undertow:
    threads:
      io: ${UNDERTOW_IO_THREADS:10}
      worker: ${UNDERTOW_IO_WORKERS:100}
  servlet:
    context-path: /api

spring:
  application:
    name: ms-accounts
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    driver-class-name: ${SPRING_DS_DRIVER:org.h2.Driver}
    url: ${SPRING_DS_URL:jdbc:h2:mem:db-itau}
    username: ${SPRING_DS_USERNAME:user_client}
    password: ${SPRING_DS_PWD:p4ssw0rd!123}
  h2:
    console:
      enabled: ${SPRING_H2_CONSOLE_ENABLED:true}
  jpa:
    database-platform: ${SPRING_JPA_DB_PLATFORM}
    generate-ddl: ${SPRING_JPA_GENERATE_DDL:false}
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: ${SPRING_JPA_PROP_HIBERNATE_SHOW_SQL:false}
        format_sql: ${SPRING_JPA_PROP_HIBERNATE_FORMAT_SQL:false}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
  pattern:
    console: "[%thread][%highlight(%-5level)][%cyan(%d{yyyy-MM-dd HH:mm:ss})][%yellow(%X{requestId})][%magenta(%logger{40})] - %msg%n"